name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          path: backend # Specify the path to the backend directory
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build Backend
        working-directory: backend
        run: |
          npm ci
          npm run build --if-present
          npm test
          
